import {
    LucideIcon,
    Server,
    Shield,
    Code,
    Cpu,
    Cloud,
    Zap,
    Lightbulb,
    ShieldCheck,
    MessageSquare,
} from 'lucide-react';

export interface Service {
    slug: string;
    icon: LucideIcon;
    logoImage: string;
    sidebarImage: string;
    bannerImage: string;
    bgColor: string;
    title: string;
    description: string;
    longDescription: string;
    features: string[];
    benefits: string[];
}

export const servicesData: Service[] = [
    {
        slug: 'digital-infrastructure',
        icon: Server,
        logoImage: '',
        sidebarImage: '',
        bannerImage: '/images/digital-infrastructure-final.png',
        bgColor: '#2E3A59',
        title: 'Digital Infrastructure',
        description: 'Reliable digital infrastructure specializing in high-performance, scalable environments.',
        longDescription: 'Reliable digital infrastructure is the backbone of any modern business. We specialize in creating high-performance environments that scale with your growth, ensuring your team has the tools they need to succeed without technical bottlenecks.',
        features: ['Network Infrastructure', 'Security Architecture', 'Scalable ICT Design', 'Managed Operations'],
        benefits: ['Improved productivity', 'Reduced downtime', 'Easy scalability', 'Cost-efficient operations'],
    },
    {
        slug: 'data-center',
        icon: Server,
        logoImage: '',
        sidebarImage: '',
        bannerImage: '/images/data-center-final.png',
        bgColor: '#1E293B',
        title: 'Data Center Solutions',
        description: 'Comprehensive data center solutions supporting facilities, IT systems, and high-availability operations.',
        longDescription: 'Comprehensive data center solutions supporting facilities, IT systems, and high-availability operations.',
        features: ['Facilities Management', 'IT Systems & Integration', 'Power & Cooling Solutions', 'Monitoring & HA Operations'],
        benefits: ['High availability', 'Advanced security', 'Energy efficiency', 'Operational resilience'],
    },
    {
        slug: 'integrated-security',
        icon: Shield,
        logoImage: '',
        sidebarImage: '',
        bannerImage: '/images/custom-cctv.jpg',
        bgColor: '#22C55E',
        title: 'Integrated Security Systems',
        description: 'End-to-end security and risk management solutions for comprehensive data and physical protection.',
        longDescription: 'End-to-end security and risk management solutions for comprehensive data and physical protection.',
        features: ['Cybersecurity & IT Security', 'CCTV & Surveillance', 'Access Control Systems', 'Threat Monitoring & Compliance'],
        benefits: ['Enhanced data protection', 'Regulatory compliance', 'Business continuity', 'Customer trust'],
    },
    {
        slug: 'enterprise-applications',
        icon: Code,
        logoImage: '/images/enterprise-apps-final.png',
        sidebarImage: '',
        bannerImage: '/images/custom-enterprise-v2.jpg',
        bgColor: '#3B82F6',
        title: 'Enterprise Platforms & Applications',
        description: 'Enterprise-grade application suites and business platforms for operational efficiency and secure service delivery.',
        longDescription: 'Enterprise-grade application suites and business platforms for operational efficiency and secure service delivery.',
        features: ['Enterprise Resource Planning (ERP)', 'Collaboration & Communication', 'Enterprise Databases', 'Business-Critical Platforms'],
        benefits: ['Tailored functionality', 'Higher efficiency', 'Seamless integration', 'Long-term flexibility'],
    },
    {
        slug: 'technology-advisory',
        icon: Lightbulb,
        logoImage: '/images/technology-advisory-logo-new.png',
        sidebarImage: '',
        bannerImage: '/images/technology-advisory-final.jpg',
        bgColor: '#8B5CF6',
        title: 'Technology Advisory & Integration',
        description: 'Professional ICT consulting and system design services to align technology with strategic goals.',
        longDescription: 'Professional ICT consulting and system design services to align technology with strategic goals.',
        features: ['Digital transformation', 'Strategy consulting', 'System optimization', 'IT roadmap development', 'ROI analysis'],
        benefits: ['Strategic alignment', 'Informed decision-making', 'Optimized investments', 'Competitive advantage'],
    },
    {
        slug: 'cloud-virtualization',
        icon: Cloud,
        logoImage: '/images/cloud-virtualization-logo-new.png',
        sidebarImage: '',
        bannerImage: '/images/custom-cloud.jpg',
        bgColor: '#38BDF8',
        title: 'Cloud & Virtualization Services',
        description: 'Scalable cloud and virtualization solutions for modernized infrastructure and business continuity.',
        longDescription: 'Scalable cloud and virtualization solutions for modernized infrastructure and business continuity.',
        features: ['Public, Private & Hybrid Cloud', 'Server & Desktop Virtualization', 'Backup & Disaster Recovery', 'Business Continuity Solutions'],
        benefits: ['Global accessibility', 'Operational agility', 'Reduced CAPEX', 'Seamless disaster recovery'],
    },
    {
        slug: 'smart-systems',
        icon: Cpu,
        logoImage: '/images/smart-systems-final.png',
        sidebarImage: '',
        bannerImage: '/images/smart-systems-final.png',
        bgColor: '#FACC15',
        title: 'Smart Systems & Automation',
        description: 'Intelligent, IoT-enabled, and connected systems for automation, monitoring, and digital transformation.',
        longDescription: 'Intelligent, IoT-enabled, and connected systems for automation, monitoring, and digital transformation.',
        features: ['Building Automation', 'Smart Lighting', 'Energy Management', 'Intelligent Security', 'Network Optimization'],
        benefits: ['Real-time insights', 'Automated efficiency', 'Predictive maintenance', 'Energy savings'],
    },
    {
        slug: 'engineering-critical-systems',
        icon: Zap,
        logoImage: '/images/critical-systems-logo-new.png',
        sidebarImage: '',
        bannerImage: '/images/engineering-electrical-final.jpg',
        bgColor: '#1C1C1C',
        title: 'Engineering & Critical Systems',
        description: 'Precision engineering for critical operations, focusing on maximum uptime, energy efficiency, and total reliability.',
        longDescription: 'Critical operations require precision engineering. We design facilities and power systems with a focus on maximum uptime, energy efficiency, and total reliability through redundant systems and robust engineering.',
        features: ['Facility engineering', 'Power optimization', 'Cooling systems', 'Redundancy planning', 'Environmental controls'],
        benefits: ['Maximum uptime', 'Energy efficiency', 'Equipment longevity', 'Future-proof design'],
    },
    {
        slug: 'cybersecurity',
        icon: ShieldCheck,
        logoImage: '/images/cyber-risk-logo-new.png',
        sidebarImage: '',
        bannerImage: '/images/custom-cybersecurity.png',
        bgColor: '#0F172A',
        title: 'Cybersecurity',
        description: 'Advanced threat protection and managed security services to safeguard your digital assets.',
        longDescription: 'Advanced threat protection, security auditing, and managed security services to safeguard your digital assets in an evolving threat landscape.',
        features: ['Threat Intelligence', 'Vulnerability Assessment', 'Incident Response', 'Managed Security (MSSP)'],
        benefits: ['Data protection', 'Regulatory compliance', 'Reduced risk', 'Business continuity'],
    },
    {
        slug: 'unified-communications',
        icon: MessageSquare,
        logoImage: '/images/unified-communications-new.png',
        sidebarImage: '',
        bannerImage: '/images/unified-communications-new.png',
        bgColor: '#1E293B',
        title: 'Unified Communications',
        description: 'Seamless integration of voice, video, and collaboration tools to enhance business connectivity.',
        longDescription: 'Seamless integration of voice, video, messaging, and collaboration tools to enhance business connectivity and team productivity.',
        features: ['IP Telephony', 'Video Conferencing', 'Team Collaboration', 'Contact Center Solutions'],
        benefits: ['Enhanced collaboration', 'Cost savings', 'Flexible working', 'Improved customer experience'],
    },
];
