import {
    Server,
    Shield,
    Code,
    Cpu,
    Cloud,
    Zap,
    Lightbulb,
} from 'lucide-react';

export const servicesData = [
    {
        slug: 'digital-infrastructure',
        icon: Server,
        logoImage: '',
        bannerImage: '/images/digital-infrastructure-bg.jpg',
        bgColor: '#2E3A59',
        title: 'Digital Infrastructure',
        description: '',
        longDescription: 'Design, deployment, and management of secure, scalable ICT infrastructure for reliable operations.',
        features: [],
        benefits: ['Improved productivity', 'Reduced downtime', 'Easy scalability', 'Cost-efficient operations'],
    },
    {
        slug: 'cyber-risk-protection',
        icon: Shield,
        logoImage: '',
        bannerImage: '/images/cyber-risk-bg-new.jpg',
        bgColor: '#22C55E',
        title: 'Integrated Security',
        description: '',
        longDescription: 'End-to-end cybersecurity, CCTV, access control, threat monitoring, risk management, and compliance solutions.',
        features: [],
        benefits: ['Enhanced data protection', 'Regulatory compliance', 'Business continuity', 'Customer trust'],
    },
    {
        slug: 'cloud-virtualization',
        icon: Cloud,
        logoImage: '',
        bannerImage: '/images/cloud and vertualization.jpg',
        bgColor: '#38BDF8',
        title: 'Cloud & Virtualization',
        description: '',
        longDescription: 'Public, private, and hybrid cloud, server and desktop virtualization, backup, disaster recovery, and business continuity solutions.',
        features: [],
        benefits: ['Global accessibility', 'Operational agility', 'Reduced CAPEX', 'Seamless disaster recovery'],
    },
    {
        slug: 'enterprise-platforms-applications',
        icon: Code,
        logoImage: '',
        bannerImage: '/images/enterprise-apps-logo.png',
        bgColor: '#3B82F6',
        title: 'Enterprise Applications',
        description: '',
        longDescription: 'ERP, collaboration, databases, and business-critical platforms for operational efficiency and secure service delivery.',
        features: [],
        benefits: ['Tailored functionality', 'Higher efficiency', 'Seamless integration', 'Long-term flexibility'],
    },
    {
        slug: 'smart-connected-systems',
        icon: Cpu,
        logoImage: '',
        bannerImage: '/images/smart-systems-detail.jpg',
        sidebarImage: '/images/sidebar-cta-bg.jpg',
        bgColor: '#FACC15',
        title: 'Smart Systems',
        description: '',
        longDescription: 'Intelligent, IoT-enabled, and connected systems for automation, monitoring, and digital transformation.',
        features: ['Building Automation', 'Smart Lighting', 'Energy Management', 'Intelligent Security', 'Network Optimization'],
        benefits: ['Real-time insights', 'Automated efficiency', 'Predictive maintenance', 'Energy savings'],
    },
    {
        slug: 'technology-advisory-integration',
        icon: Lightbulb,
        logoImage: '',
        bannerImage: '/images/technology-advisory-bg-new.jpg',
        bgColor: '#8B5CF6',
        title: 'Technology Advisory',
        description: '',
        longDescription: 'Professional ICT consulting, system design, integration, project management, and interoperability services.',
        features: [],
        benefits: ['Strategic alignment', 'Informed decision-making', 'Optimized investments', 'Competitive advantage'],
    },
    {
        slug: 'data-centers',
        icon: Server,
        logoImage: '',
        bannerImage: '/images/data-center-clean.jpg',
        bgColor: '#1E293B',
        title: 'Data Centers',
        description: '',
        longDescription: 'Full data center solutions including facilities, IT systems, power, cooling, monitoring, and high-availability operations.',
        features: [],
        benefits: ['High availability', 'Advanced security', 'Energy efficiency', 'Scalable infrastructure'],
    },
    {
        slug: 'engineering-electrical',
        icon: Zap,
        logoImage: '',
        bannerImage: '/images/engineering-critical-systems-bg.jpg',
        bgColor: '#0F172A',
        title: 'Engineering & Electrical',
        description: '',
        longDescription: 'Electrical, power, low-current, and mission-critical infrastructure supporting ICT, operational, and data center environments.',
        features: [],
        benefits: ['Reliable power systems', 'Expert engineering', 'Safety compliance', 'Operational resilience'],
    },
];
