import {
    Server,
    Shield,
    Code,
    Cpu,
    Cloud,
    Zap,
    Lightbulb,
} from 'lucide-react';

export const servicesData = [
    {
        slug: 'digital-infrastructure',
        icon: Server,
        title: 'Digital Infrastructure',
        description: 'Designing and deploying scalable, secure, and high-performance network and IT environments.',
        longDescription: 'Reliable digital infrastructure is the backbone of any modern business. We specialize in creating high-performance environments that scale with your growth, ensuring your team has the tools they need to succeed without technical bottlenecks.',
        features: ['Scalable networks', 'Secure hardware', 'High-performance setup', 'Network monitoring', 'Server virtualization'],
        benefits: ['Improved productivity', 'Reduced downtime', 'Easy scalability', 'Cost-efficient operations'],
    },
    {
        slug: 'cyber-risk-protection',
        icon: Shield,
        logoImage: '/images/cyber-risk-protection-logo.png',
        title: 'Cyber & Risk Protection',
        description: 'Protecting digital assets through advanced security architecture, risk management, and threat mitigation.',
        longDescription: 'In an era of increasing digital threats, our Cyber & Risk Protection services provide a comprehensive defense strategy for your enterprise. We focus on building resilient architectures that not only block attacks but also ensure rapid recovery.',
        features: ['Security architecture', 'Risk management', 'Threat mitigation', 'Compliance auditing'],
        benefits: ['Enhanced data protection', 'Regulatory compliance', 'Business continuity', 'Customer trust'],
    },
    {
        slug: 'enterprise-platforms-applications',
        icon: Code,
        title: 'Enterprise Platforms & Applications',
        description: 'Building reliable, secure, and customized enterprise applications that support business growth.',
        longDescription: 'We build custom, secure, and scalable enterprise platforms designed to streamline your specific workflows and drive operational excellence, ensuring your software ecosystem supports your strategic goals.',
        features: ['Custom applications', 'Enterprise scale', 'Reliable code', 'API integration', 'Legacy modernization'],
        benefits: ['Tailored functionality', 'Higher efficiency', 'Seamless integration', 'Long-term flexibility'],
    },
    {
        slug: 'smart-connected-systems',
        icon: Cpu,
        title: 'Smart & Connected Systems',
        description: 'Delivering IoT-driven and intelligent systems for automation, monitoring, and efficiency.',
        longDescription: 'Leverage the power of connected systems to transform your operations. Our smart solutions provide real-time data and automation that lead to smarter decisions and more efficient processes across your facilities.',
        features: ['IoT integration', 'Automation systems', 'Intelligent monitoring', 'Data analytics', 'Remote management'],
        benefits: ['Real-time insights', 'Automated efficiency', 'Predictive maintenance', 'Energy savings'],
    },
    {
        slug: 'cloud-hybrid-enablement',
        icon: Cloud,
        title: 'Cloud & Hybrid Enablement',
        description: 'Implementing secure public, private, and hybrid cloud solutions for modern enterprises.',
        longDescription: 'Transitioning to the cloud should be seamless and secure. We help you choose and implement the right cloud strategy—public, private, or hybrid—to increase agility and reduce infrastructure overhead.',
        features: ['Public & Private cloud', 'Hybrid setups', 'Secure migration', 'Cloud optimization', 'Multi-cloud strategy'],
        benefits: ['Global accessibility', 'Operational agility', 'Reduced CAPEX', 'Seamless disaster recovery'],
    },
    {
        slug: 'engineering-critical-systems',
        icon: Zap,
        title: 'Engineering & Critical Systems',
        description: 'Engineering resilient facilities and power systems for maximum uptime and reliability.',
        longDescription: 'Critical operations require precision engineering. We design facilities and power systems with a focus on maximum uptime, energy efficiency, and total reliability through redundant systems and robust engineering.',
        features: ['Facility engineering', 'Power optimization', 'Cooling systems', 'Redundancy planning', 'Environmental controls'],
        benefits: ['Maximum uptime', 'Energy efficiency', 'Equipment longevity', 'Future-proof design'],
    },
    {
        slug: 'technology-advisory-integration',
        icon: Lightbulb,
        title: 'Technology Advisory & Integration',
        description: 'Advising organizations on digital transformation, system optimization, and technology strategy.',
        longDescription: 'Navigate the complex technology landscape with confidence. Our consultants work closely with your leadership to define strategies that align technology investments with your long-term business goals.',
        features: ['Digital transformation', 'Strategy consulting', 'System optimization', 'IT roadmap development', 'ROI analysis'],
        benefits: ['Strategic alignment', 'Informed decision-making', 'Optimized investments', 'Competitive advantage'],
    },
];
